In [8]:
import pandas as pd
pd.set_option('display.width', None)

In [9]:
cas3 = pd.read_csv("data/Cas3_total.csv", encoding="utf-8")

In [10]:
sample_50pct = cas3.sample(frac=0.5, random_state=42)
display(sample_50pct.head(10))

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
73,8.837875,51.538834,-5.954,-1.253,6.460,662.2,61.7,-14.83,4.25,0.00
280,9.125167,51.551029,4.762,-0.522,4.875,618.9,53.0,-122.81,4.05,0.00
25,9.012125,51.575165,0.546,0.927,1.932,322.8,50.6,-374.63,4.41,1.00
255,9.273791,51.557529,10.306,-0.132,10.310,287.1,41.6,-57.10,3.41,0.00
9,9.071042,51.565582,2.743,0.352,2.832,226.2,44.3,-382.76,5.04,1.00
101,8.968458,51.562557,-1.083,0.170,1.135,255.2,50.4,-367.74,4.81,1.00
176,8.771167,51.605335,-8.443,2.737,10.062,357.3,45.5,-225.92,4.65,0.00
186,9.017041,51.614887,0.729,3.310,6.660,374.6,49.1,-103.18,4.74,0.00
63,8.876917,51.523804,-4.498,-2.155,6.230,515.2,59.2,-387.90,3.92,1.00
116,9.030666,51.549194,1.237,-0.632,1.768,207.7,44.9,-351.23,3.61,0.99

In [11]:
sample_10pct = cas3.sample(frac=0.5, random_state=42)
display(sample_10pct.head(10))

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
73,8.837875,51.538834,-5.954,-1.253,6.460,662.2,61.7,-14.83,4.25,0.00
280,9.125167,51.551029,4.762,-0.522,4.875,618.9,53.0,-122.81,4.05,0.00
25,9.012125,51.575165,0.546,0.927,1.932,322.8,50.6,-374.63,4.41,1.00
255,9.273791,51.557529,10.306,-0.132,10.310,287.1,41.6,-57.10,3.41,0.00
9,9.071042,51.565582,2.743,0.352,2.832,226.2,44.3,-382.76,5.04,1.00
101,8.968458,51.562557,-1.083,0.170,1.135,255.2,50.4,-367.74,4.81,1.00
176,8.771167,51.605335,-8.443,2.737,10.062,357.3,45.5,-225.92,4.65,0.00
186,9.017041,51.614887,0.729,3.310,6.660,374.6,49.1,-103.18,4.74,0.00
63,8.876917,51.523804,-4.498,-2.155,6.230,515.2,59.2,-387.90,3.92,1.00
116,9.030666,51.549194,1.237,-0.632,1.768,207.7,44.9,-351.23,3.61,0.99

In [12]:
lac=pd.read_csv("data/Lac1_total.csv", encoding="utf-8")
sample_50pct = cas3.sample(frac=0.5, random_state=42)
display(sample_50pct.head(3))
sample_10pct = cas3.sample(frac=0.5, random_state=42)
display(sample_10pct.head(3))

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
73,8.837875,51.538834,-5.954,-1.253,6.460,662.2,61.7,-14.83,4.25,0.0
280,9.125167,51.551029,4.762,-0.522,4.875,618.9,53.0,-122.81,4.05,0.0
25,9.012125,51.575165,0.546,0.927,1.932,322.8,50.6,-374.63,4.41,1.0

,ra,dec,xki,eta,radius,signal,noise,vr,e_vr,P(member)
73,8.837875,51.538834,-5.954,-1.253,6.460,662.2,61.7,-14.83,4.25,0.0
280,9.125167,51.551029,4.762,-0.522,4.875,618.9,53.0,-122.81,4.05,0.0
25,9.012125,51.575165,0.546,0.927,1.932,322.8,50.6,-374.63,4.41,1.0